plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
        }

        register('client')
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    from "src/main/templates"
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata

tasks.register('verifyClientState', JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'cn.ussshenzhou.hotbaaaar.client.ClientStateTestSuite'
}

tasks.named('check').configure {
    dependsOn verifyClientState
}

tasks.named('test', Test).configure {
    failOnNoDiscoveredTests = false
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes 'MixinConfigs': "${mod_id}.mixins.json"
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
}
